### ISSUE TITLE
Colours not stripping and feature request

### ISSUE THREAD

**Issue by Pawned** [the-obsidian/DiscordBridge#4]
After finally getting this working (thanks guys!) I've noticed that colours aren't being stripped, although I know you added this in one of the updates. See example below:

[Minecraft] Pawned: ?8[?2L?8] [?4Founder?8]?f Pawned?4:?f Pawnbot has been fixed 😃

Also was just thinking it would maybe be good to hook into Discord's join/afk/leave events too (if that's possible with the current API) and post that in Minecraft?

Also when you do @person in Discord it displays at @UUID in Minecraft. Any way this can just stay as @person or is this a limit in the API?

**Comment by jacobwgillespie** [comment]
Looks like I may be hooking into the wrong part of the Minecraft message, since the part I'm considering the text looks like it contains your username and prefixes.

Yeah, I think it's possible to hook into Discord join/leave.  I'll add that as an optional feature.

I'll look into mentions.  What I really want to do eventually is have a feature where either on Minecraft or on Discord, you have the option of being PM'd by the bot user with a special code (like `/discord 23sdf234`) that "links" your Discord and Minecraft users so that usernames translate between the systems.  In my case, if I talk as `jacobwg` on Minecraft it'll show up as `jacobwgillespie` on Discord, and vice versa.  @-mentions could be included in that feature.

**Comment by Pawned** [comment]
Yeah, if you just strip event.getMessage() it should do the job.

That would be cool with the username synchronisation. One feature that was pretty cool with CraftIRC was that you could also execute some commands in IRC, prefixed with an @ instead of a / such as `@who` and this would retrieve the list of players in-game and show it in IRC. Would be pretty cool if you could replicate this functionality at some point in the future as well.

**Comment by jacobwgillespie** [comment]
Colors should be stripped now in v1.4.0: https://github.com/the-obsidian/DiscordBridge/releases/tag/v1.4.0
